Many fix
lidofinance/aave-collaterals-bot pull request #93
Opened 2023-09-20 03:33 UTC by first-leon

Update configs.
Change prometheus rule.
Change default connection NODE_ENDPOINT timeout.

2023-09-20 06:55 UTC, madlabman requested changes

2023-09-20 06:55 UTC, madlabman commented on src/bot/eth.py
> +w3 = Web3(HTTPProvider(NODE_ENDPOINT, request_kwargs={'timeout': 90}))
Run `black` formatter, please. It will blow up linters otherwise.

2023-09-20 06:55 UTC, madlabman commented on docker-compose.yml
> +  bot-collaterals:
I think `mainnet` fits better here.

2023-09-20 06:55 UTC, madlabman commented on prometheus/scrape_config/arbitrum.yml
> +          env: 'prod'
Please run `prettier` to make the file consistent.

2023-09-20 06:55 UTC, madlabman commented on prometheus/status.rule
> +        expr: changes(process_start_time_seconds{job=~"collaterals|arbitrum|polygon"}[15m]) >= 3
```suggestion
        expr: changes(process_start_time_seconds{job=~"mainnet|arbitrum|polygon"}[15m]) >= 3
```

or `ethereum`

2023-09-20 07:02 UTC, madlabman commented
Please add tests for the updated rules.

2023-09-22 09:16 UTC, madlabman requested changes

2023-09-22 09:16 UTC, madlabman commented on prometheus/status.rule
> +          absent(aave_bot_processing_finished_seconds{job=~"mainnet"})
```suggestion
          absent(aave_bot_processing_finished_seconds{job=~"mainnet|arbitrum|polygon"})
```

2023-09-22 09:16 UTC, madlabman commented on prometheus/status.rule
> +          summary: Stale AAVE (mainnet|arbitrum|polygon) bot report detected
```suggestion
          summary: Stale AAVE {{ $labels.job }} bot report detected
```

2023-09-22 09:16 UTC, madlabman commented on prometheus/status.rule
> +            minutes since the AAVE (mainnet|arbitrum|polygon) bot was launched
```suggestion
            minutes since the AAVE {{ $labels.job }} bot was launched
```

2023-09-22 09:16 UTC, madlabman commented on prometheus/status.test
> +              summary: Stale AAVE (mainnet|arbitrum|polygon) bot report detected
```suggestion
              summary: Stale AAVE mainnet bot report detected
```

2023-09-22 09:16 UTC, madlabman commented on prometheus/status.test
> +                minutes since the AAVE (mainnet|arbitrum|polygon) bot was launched
```suggestion
                minutes since the AAVE mainnet bot was launched
```

2023-09-22 09:17 UTC, madlabman commented
Route the PR to `develop`

2023-10-03 12:45 UTC, madlabman commented
Please close this PR in favor of #95

2023-10-03 12:46 UTC, madlabman approved these changes

2023-10-03 12:47 UTC, madlabman requested changes
.

2023-10-03 12:51 UTC, first-leon commented
Solution in https://github.com/lidofinance/aave-collaterals-bot/pull/95

2023-10-03 12:51 UTC, closed without merging